### ISSUE TITLE
 EthernetDataLinkChannelIterator method next() panic: 'called `Option::unwrap()`

### ISSUE THREAD

**Issue by 0x0G** [libpnet/libpnet#202]
I do not know how to reproduce the error exactly, but from time to time, this error occurs:

```shell
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:325
stack backtrace:
   0:     0x7ff745476b7c - std::rt::lang_start::hfe4efe1fc39e4a30
   1:     0x7ff745476189 - std::rt::lang_start::hfe4efe1fc39e4a30
   2:     0x7ff74546897d - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   3:     0x7ff7454791bb - rust_begin_unwind
   4:     0x7ff74546997f - std::panicking::begin_panic_fmt::hdddb415186c241e7
   5:     0x7ff745478dfc - rust_begin_unwind
   6:     0x7ff74547bcf5 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
   7:     0x7ff74547bff0 - core::panicking::panic::h907815f47e914305
   8:     0x7ff7453a108c - unwrap<(usize, usize)>
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libcore\macros.rs:21
   9:     0x7ff7453a079e - next
                        at C:\Users\.cargo\registry\src\github.com-1ecc6299db9ec823\pnet-0.10.0\src\datalink\winpcap.rs:279
  10:     0x7ff745375600 - handle
                        at C:\Users\projects\rust\packet_helper\src\main.rs:112
  11:     0x7ff7453712bc - main
                        at C:\Users\projects\rust\packet_helper\src\main.rs:62
  12:     0x7ff745475b7c - std::rt::lang_start::hfe4efe1fc39e4a30
  13:     0x7ff745479251 - _rust_maybe_catch_panic
  14:     0x7ff7454758b4 - std::rt::lang_start::hfe4efe1fc39e4a30
  15:     0x7ff745375c59 - main
  16:     0x7ff745480a6f - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:255
  17:     0x7ff817128101 - BaseThreadInitThunk
error: Process didn't exit successfully: `target\debug\packet_helper.exe` (exit code: 101)
```

This is packet_helper\src\main.rs:112 line:

```rust
let packet = iter.next().chain_err(|| "Unable to receive packet")?;
```

This is full code:

```rust
fn main() {
    // Find the network interface with the provided name
    let interfaces = get_network_interfaces();
    let interface = interfaces.into_iter()
        .next()
        .ok_or("interface not found".into())
        .unwrap_or_else(|e| exit_with_error(e));

    handle(&interface)
        .chain_err(|| format!("Can not handle packet from interface; interface = {}", &interface.name[..]))
        .unwrap_or_else(|e| exit_with_error(e));
}

fn handle(interface: &NetworkInterface) -> Result<()> {
    // Create a new channel, dealing with layer 2 packets
    let channel = datalink::channel(interface, &Default::default()).chain_err(|| "An error occurred when creating the datalink channel")?;
    let (mut _tx, mut rx) = match channel {
        Ethernet(tx, rx) => (tx, rx),
        _ => return Err("Unhandled channel type".into()),
    };

    let mut iter = rx.iter();
    loop {
        let packet = iter.next().chain_err(|| "Unable to receive packet")?;
        handle_packet(&interface.name[..], &packet)?;
    }
}

fn handle_packet(interface_name: &str, ethernet: &EthernetPacket) -> Result<()> {
    match ethernet.get_ethertype() {
        EtherTypes::Ipv4 => handle_ipv4_packet(interface_name, ethernet),
        _ => {
            trace!("[{}]: Not supported Ethernet packet: {} > {}; ethertype: {:?} length: {}",
                   interface_name,
                   ethernet.get_source(),
                   ethernet.get_destination(),
                   ethernet.get_ethertype(),
                   ethernet.packet().len());
            Ok(())
        }
    }
}

fn handle_ipv4_packet(interface_name: &str, ethernet: &EthernetPacket) -> Result<()> {
    let header = Ipv4Packet::new(ethernet.payload()).ok_or("Malformed IPv4 Packet")?;
    handle_transport_protocol(interface_name,
                              IpAddr::V4(header.get_source()),
                              IpAddr::V4(header.get_destination()),
                              header.get_next_level_protocol(),
                              header.payload())
}

fn handle_transport_protocol(interface_name: &str, source: IpAddr, destination: IpAddr, protocol: IpNextHeaderProtocol, packet: &[u8]) -> Result<()> {
    match protocol {
        IpNextHeaderProtocols::Tcp => handle_tcp_packet(interface_name, source, destination, packet),
        _ => {
            trace!("[{}]: Not supported transport packet: {} > {}; protocol: {:?} length: {}",
                   interface_name,
                   source,
                   destination,
                   protocol,
                   packet.len());
            Ok(())
        }
    }
}

fn handle_tcp_packet(interface_name: &str, source: IpAddr, destination: IpAddr, packet: &[u8]) -> Result<()> {
    let tcp = TcpPacket::new(packet).ok_or("Malformed TCP Packet")?;

...

    Ok(())
}
```

OS: Windows 10
rustc 1.11.0-nightly (1ab87b65a 2016-07-02)

**Comment by mrmonday** [comment]
It looks like `winpcap::PacketReceivePacket()` is returning success when there are no packets to receive - I don't know why that would happen. I don't have access to a Windows machine right now to try and reproduce this, I'll bare it in mind for next time I'm near one. Thanks for the bug report.
