### ISSUE TITLE
Out of bounds check and reliability

### ISSUE THREAD

**Issue by polachok** [libpnet/libpnet#221]
It's super easy to crash libpnet with invalid packets:

```rust
extern crate pnet;
use pnet::packet::tcp::{TcpPacket, MutableTcpPacket, MutableTcpOptionPacket, TcpOptionNumbers, TcpFlags};

fn main() {
    let mut buf = [0;20];
    {
        if let Some(mut tcp) = MutableTcpPacket::new(&mut buf[..]) {
            tcp.set_data_offset(10);
        }
    }

    if let Some(tcp) = TcpPacket::new(&buf[..]) {
        let options = tcp.get_options_iter();
    }
}
```

Result:
```
thread 'main' panicked at 'index 40 out of range for slice of length 20', ../src/libcore/slice.rs:549
stack backtrace:
   1:     0x7f2f47f85b6f - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x7f2f47f87f6b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x7f2f47f87bef - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x7f2f47f8242e - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x7f2f47f881b1 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x7f2f47f8291a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x7f2f47f8814e - rust_begin_unwind
   8:     0x7f2f47fbd13f - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x7f2f47fbd3b3 - core::slice::slice_index_len_fail::ha4faf37254d75f20
  10:     0x7f2f47f810e1 - core::slice::_<impl core..ops..Index<core..ops..Range<usize>> for [T]>::index::h03ea1b16a47c3727
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/slice.rs:579
  11:     0x7f2f47f80fea - pnet::packet::tcp::TcpPacket::get_options_iter::h4058aa4c141e080f
                        at /tmp/pnet-out-of-bounds/target/debug/build/pnet-81bd5cb98b679239/out/tcp.rs:302
  12:     0x7f2f47f80ab2 - pnet_out_of_bounds::main::h37e2c15174819b76
                        at /tmp/pnet-out-of-bounds/src/main.rs:13
```

Obviously in my real code I don't create bad packet on purpose but receive it from the network.
So, do you think it makes sense to add checks to libpnet or is it supposed to be handled by application developer?

**Comment by mrmonday** [comment]
Part of #141 (I believe there are a couple of other issues which fall into this category too) - Ideally I want libpnet to never panic when parsing a packet. Invalid packets are fine (that's up to the application developer), but none of the generated accessors or mutators should panic.

**Comment by polachok** [comment]
Understood, I'll send a PR for this later

**Comment by mrmonday** [comment]
What a :star2:, thank you!
