### ISSUE TITLE
Infinite loop in TCP options parsing

### ISSUE THREAD

**Issue by SalmonProject** [libpnet/libpnet#260]
This function:
```
pub fn extract_from(the_options: TcpOptionIterable) -> WscaleAndMSS
{
    let mut ret = WscaleAndMSS::default();
    for opt in the_options {
        if opt.get_number() == TcpOptionNumbers::WSCALE {
            ret.wscale = opt.payload()[0];
        }
        else if opt.get_number() == TcpOptionNumbers::MSS {
            let payload = opt.payload();
            ret.mss = ((payload[0] as u16) << 8) | (payload[1] as u16);
        }
    }
    ret
}
```

called by `WscaleAndMSS::extract_from(tcp_pkt.get_options_iter())` gets stuck in an infinite loop (100% CPU spinning) on ~one in a few billion packets seen on the internet.

I believe this is the correct way of using pnet's TCP options parsing (if not, apologies for the spurious report!). Unfortunately, we don't have a practical way to record the packets that cause this problem.

**Comment by polachok** [comment]
Looks correct, i'm using almost [same code](https://github.com/LTD-Beget/syncookied/blob/master/src/packet.rs#L208) in my project.
Would be great if you provided the packet causing this problem.

**Comment by SalmonProject** [comment]
We decided to leave things as they are, but with a workaround (just breaking the loop after too many iterations). With that workaround, it ought to be practical to record offending packets. Assuming we do see more of these packets, I'll try to get one, and post it here.

**Comment by SalmonProject** [comment]
Can't provide a packet yet, but I can confirm that there is definitely something broken. `println!("BAD PACKET: {:?}", tcp_pkt);` panics, where `tcp_pkt` is the `tcp_pkt` from my original post, and this line is called if `catch_unwind(extract_from(tcp_pkt.get_options_iter())` returns an `Err`.

**Comment by polachok** [comment]
Can you dump &[u8] for the packet?

**Comment by SalmonProject** [comment]
Got one! This is the .payload() of the enclosing Ipv4Packet, which is what the offending TcpPacket was built from with TcpPacket::new().
BAD PACKET: [192, 8, 1, 187, 11, 135, 230, 126, 0, 0, 0, 0, 176, 2, 255, 255, 213, 46, 0, 0, 2, 4, 5, 244, 2, 3, 3, 5, 1, 1, 8, 10, 21, 181, 4, 0, 0, 0, 0, 0, 4, 2, 0, 0]

**Comment by polachok** [comment]
Running
```rust
#[cfg(test)]
mod tests {
    extern crate pnet;

    use self::pnet::packet::Packet;
    use self::pnet::packet::ipv4::Ipv4Packet;
    use self::pnet::packet::tcp::TcpPacket;
    #[test]
    fn it_works() {
        let bytes: [u8; 44] = [192, 8, 1, 187, 11, 135, 230, 126, 0, 0, 0, 0, 176, 2, 255, 255, 213, 46, 0, 0, 2, 4, 5, 244, 2, 3, 3, 5, 1, 1, 8, 10, 21, 181, 4, 0, 0, 0, 0, 0, 4, 2, 0, 0];
        let ipv4 = Ipv4Packet::new(&bytes[..]).unwrap();
        let tcp = TcpPacket::new(ipv4.payload());
    }
}
```

I get

```
running 1 test
test tests::it_works ... FAILED

failures:

---- tests::it_works stdout ----
        thread 'tests::it_works' panicked at 'attempt to subtract with overflow', /home/plhk/libpnet-bad-packet/target/debug/build/pnet-9c269aa7ffe1b236/out/ipv4.rs:1237
stack backtrace:
   1:     0x55f2c94ab82c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55f2c94ae97e - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55f2c94ae523 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x55f2c94aee1b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x55f2c94aecb4 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x55f2c94aebd9 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x55f2c94aeb67 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x55f2c94d997d - core::panicking::panic_fmt::hc0f6d7b2c300cdd9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55f2c94d98b4 - core::panicking::panic::h7abeb5b818ec354e
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x55f2c946ed43 - pnet::packet::ipv4::ipv4_options_length::h95eb851f6dd11e4e
                        at /home/plhk/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/pnet-0.17.0/src/packet/ipv4.rs:12
  11:     0x55f2c946e104 - <pnet::packet::ipv4::Ipv4Packet<'a> as pnet::packet::Packet>::payload::h4b29c4f318958671
                        at /home/plhk/libpnet-bad-packet/target/debug/build/pnet-9c269aa7ffe1b236/out/ipv4.rs:1038
  12:     0x55f2c946e3f2 - libpnet_bad_packet::tests::it_works::hdefad344c6e64ece
                        at /home/plhk/libpnet-bad-packet/src/lib.rs:12
  13:     0x55f2c947d02e - <F as test::FnBox<T>>::call_box::he0ddef732487ab41
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libtest/lib.rs:1366
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libtest/lib.rs:140
  14:     0x55f2c94b5d2a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  15:     0x55f2c947141a - std::panicking::try::do_call::h4652d5e10f648844
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libtest/lib.rs:1311
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:296
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:460
  16:     0x55f2c94b5d2a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  17:     0x55f2c9478046 - <F as alloc::boxed::FnBox<A>>::call_box::h274e3783c3771bc8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:614
  18:     0x55f2c94adc84 - std::sys::imp::thread::Thread::new::thread_start::he668872ac11287ba
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:624
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  19:     0x7fc3a225e181 - start_thread
  20:     0x7fc3a1d7547c - __clone
  21:                0x0 - <unknown>
```
Already found by #250

**Comment by SalmonProject** [comment]
Oh, great! I will close this, then. Good job over there, looking forward to getting all of those fixes in a release.
