### ISSUE TITLE
'Option::unwrap() on None' panic in netmap datalink module

### ISSUE THREAD

**Issue by gclinch** [libpnet/libpnet#276]
It seems that either nm_nextpkt returns a too-short buffer, or can return null even after having been polled (datalink/netmap.rs:255).

```
thread 'eno2' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
stack backtrace:
   1:     0x55771cb7ba0a - std::sys::imp::backtrace::tracing::imp::write::hd9cb4c1797101742
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55771cb7ec1f - std::panicking::default_hook::{{closure}}::h154dea97b11a961f
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:349
   3:     0x55771cb7e824 - std::panicking::default_hook::h7b2373844128ce08
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:365
   4:     0x55771cb7f0c7 - std::panicking::rust_panic_with_hook::h8d52d23c1df454da
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:553
   5:     0x55771cb7ef04 - std::panicking::begin_panic::h031e0a076e248818
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:515
   6:     0x55771cb7ee79 - std::panicking::begin_panic_fmt::hcd972326ec953c01
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:499
   7:     0x55771cb7ee07 - rust_begin_unwind
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:475
   8:     0x55771cbb31dd - core::panicking::panic_fmt::h519452995771b90d
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libcore/panicking.rs:69
   9:     0x55771cbb3114 - core::panicking::panic::h22b1ce4468ab1d51
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libcore/panicking.rs:49
  10:     0x55771cafca16 - <core::option::Option<T>>::unwrap::hff96b94e047d6bd6
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libcore/macros.rs:21
  11:     0x55771cb059cc - <pnet::datalink::backend::DataLinkChannelIteratorImpl<'a> as pnet::datalink::EthernetDataLinkChannelIterator<'a>>::next::hcbd3295c0cca8067
                        at /home/clinch/.cargo/registry/src/github.com-1ecc6299db9ec823/pnet-0.18.0/src/datalink/netmap.rs:257
  12:     0x55771c8e914a - snitch::capture::capture_on_interface::{{closure}}::haaaeb000c72d819d
                        at /home/clinch/proj/snitch/src/capture.rs:72
  13:     0x55771c8e60f0 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h50e318e11ee8cc95
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panic.rs:295
  14:     0x55771c8b9f93 - std::panicking::try::do_call::he456e9a6c8ae3aff
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:458
  15:     0x55771cb878ea - __rust_maybe_catch_panic
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libpanic_unwind/lib.rs:98
  16:     0x55771c8b9bf1 - std::panicking::try::h5f35a65005ed9f45
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:434
  17:     0x55771c8b8cc4 - std::panic::catch_unwind::hb56872d2e429b65c
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panic.rs:351
  18:     0x55771c8b9826 - std::thread::Builder::spawn::{{closure}}::h2cd7f93ecaa1deff
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/thread/mod.rs:301
  19:     0x55771c8d7ace - <F as alloc::boxed::FnBox<A>>::call_box::hb2cc56d9f38dd74b
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/liballoc/boxed.rs:605
  20:     0x55771cb7df64 - std::sys::imp::thread::Thread::new::thread_start::hc88703e10b184eab
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/liballoc/boxed.rs:615
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/sys_common/thread.rs:21
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/sys/unix/thread.rs:84
  21:     0x7f61268e46b9 - start_thread
  22:     0x7f61264043dc - clone
  23:                0x0 - <unknown>
```

**Comment by mrmonday** [comment]
Unfortunately I don't have a machine with netmap support any more - is there any chance you could look into this for me?

I'll take a look later and see if I can spot anything without having to actually run it.

@polachok uses/used netmap - perhaps you wouldn't mind taking a look too, @polachok?

**Comment by gclinch** [comment]
Further investigation showed nm_nextpkt occasionally returning a very short buffer ('h.len' values lower than 10).  Disabling generic-receive-offload (gro) on the affected interface using ethtool stopped these short packets being delivered through nm_nextpkt.

Potentially EthernetDataLinkChannelIterator's next method could return an Err when EthernetPacket::new returns None, but all of the datalink receivers follow this same pattern of unwrapping EthernetPacket::new, such that any short buffer would cause cause this failure - it's not specific to netmap.

So this netmap-specific issue can be closed with the fix being to ensure generic receive offload is disabled on an netmap controlled interface.

**Comment by mrmonday** [comment]
I think there are a couple of things to take away from this:

 * I'd appreciate it if you could update the documentation with the command you used to disable GRO, so that others can benefit from this knowledge
 * I consider any panic to be a bug in libpnet - it should not fail when malformed packets are received. Without seeing the packets involved, I'm not sure what the correct course of action is here.

**Comment by TheLostLambda** [comment]
Hello!

I have absolutely no idea if this has been addressed in the past 3 years, or if that this fix was ever added to the documentation, but I've come here after following a bug all the way from Bandwhich (which is built on a fork of libpnet). In our case, we haven't run into any panic, but (I'm 90% sure) we've been missing packets from pnet (which, apparently, are dropped by netmap).

In our case, the issue has been generic receive offload as well. As a curiosity, is it possible to tell pnet to use something other than netmap on netmap-enabled hardware? Obviously some programs on my computer are able to report correct bandwidth usages, so are they using something other than netmap for the same interface? Sorry if these questions are a bit naïve.

In the spirit of documentation, here are some links that I tracked down:

- https://github.com/luigirizzo/netmap/issues/268
- https://lwn.net/Articles/358910/

And the command for disabling all "offloading" on a given interface:
```bash
# ethtool -K eth0 tx off rx off gso off tso off gro off lro off
```

Thank you so much for all of your hard work and I hope you are well!
