### ISSUE TITLE
pnet_packet 0.25 panic in pnet_packet::ipv4::checksum

### ISSUE THREAD

**Issue by chifflier** [libpnet/libpnet#399]
Upgrade to 0.25 broke things, for ex I got a panic in ipv4::checksum:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,                                                                                                                                                           
 right: `1`: Cannot sum mis-aligned words at 0x7b2145203865', /home/pollux/.cargo/registry/src/github.com-1ecc6299db9ec823/pnet_packet-0.25.0/src/util.rs:71:5
stack backtrace:         
   0: backtrace::backtrace::libunwind::trace 
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized                                                                                                                       
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write                                                             
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt                                                    
             at src/libstd/io/mod.rs:1412 
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}                                                                                                                        
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook                                                                                                                             
             at src/libstd/panicking.rs:464                   
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:328
  13: pnet_packet::util::checksum
             at /home/pollux/.cargo/registry/src/github.com-1ecc6299db9ec823/pnet_packet-0.25.0/src/util.rs:71
  14: pnet_packet::ipv4::checksum
             at ./target/debug/build/pnet_packet-a197587747d07883/out/ipv4.rs:1226
```

The same code works with 0.23

Unfortunately, I cannot downgrade my dependencies to 0.23 because of #398

**Comment by chifflier** [comment]
Hmm, this one seems caused by aecd0c51
Is the check necessary ? I read packets from a pcap file, they are not necessarily aligned

**Comment by JuxhinDB** [comment]
Hey @chifflier thanks for reporting this. You are correct, that seems to be the root cause. I should've have caught that prior to merging..

Will see what I can do to fix it. Unfortunately I'm packed right now. If you want to open a PR to fix it we can take a look at it together

**Comment by chifflier** [comment]
I'm not sure exactly how to fix that.
The `checksum` function calls `sum_be_words`, which casts the pointer to an array of `u16`, so the alignment check is indeed required here.
Would you agree to a patch that changes `sum_be_words` to work with unaligned data (just checking the first byte as initial sum value if unaligned, then working on the rest, which would be aligned) ?

**Comment by chifflier** [comment]
Oh, I missed #403 (rebase mistake), sorry for that.

Closing (but still, the comment on dependencies still stands :) )
