### ISSUE TITLE
get_socket_receive_timeout resulted in error: Bad file descriptor (os error 9)

### ISSUE THREAD

**Issue by ignatenkobrain** [libpnet/libpnet#412]
```rust
running 5 tests
test imp::tests::test_duration_to_timespec ... ok
test tests::test_get_socket_receive_timeout ... FAILED
test tests::test_set_socket_receive_timeout_1500ms ... FAILED
test tests::test_set_socket_receive_timeout_1s ... FAILED
test tests::test_set_socket_receive_timeout_500ms ... FAILED

failures:

---- tests::test_get_socket_receive_timeout stdout ----
thread 'tests::test_get_socket_receive_timeout' panicked at 'get_socket_receive_timeout resulted in error: Bad file descriptor (os error 9)', src/lib.rs:301:23

---- tests::test_set_socket_receive_timeout_1500ms stdout ----
thread 'tests::test_set_socket_receive_timeout_1500ms' panicked at 'set_socket_receive_timeout reslted in error: Bad file descriptor (os error 9)', src/lib.rs:285:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- tests::test_set_socket_receive_timeout_1s stdout ----
thread 'tests::test_set_socket_receive_timeout_1s' panicked at 'set_socket_receive_timeout reslted in error: Bad file descriptor (os error 9)', src/lib.rs:255:23

---- tests::test_set_socket_receive_timeout_500ms stdout ----
thread 'tests::test_set_socket_receive_timeout_500ms' panicked at 'set_socket_receive_timeout reslted in error: Bad file descriptor (os error 9)', src/lib.rs:270:23


failures:
    tests::test_get_socket_receive_timeout
    tests::test_set_socket_receive_timeout_1500ms
    tests::test_set_socket_receive_timeout_1s
    tests::test_set_socket_receive_timeout_500ms

test result: FAILED. 1 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by JuxhinDB** [comment]
Hi, please give some more context to the issue, including a minimal working example, what behavior you were expecting and what actual behavior occurred. Once you have this in place, feel free to re-open this issue.

**Comment by ignatenkobrain** [comment]
There is no minimal working example, you simply run `cargo test` and it fails.

**Comment by musicinmybrain** [comment]
I believe the original reporter was working on a [Rust library crate package](https://src.fedoraproject.org/rpms/rust-pnet_sys) for Fedora.

I can still reproduce the original report today, even if I update to the current 0.34.0 releases, but only in a [`mock` chroot](https://rpm-software-management.github.io/mock/), not simply by checking out the repository and running `cargo test`. Oddly, I still see these failures even if I pass the `--enable-network` option to a local `mock` build. Still, it’s likely that this has *something* to do with the `mock` environment.
