### ISSUE TITLE
TcpPacket::packet_size Calculates Options Size Incorrectly

### ISSUE THREAD

**Issue by riesentoaster** [libpnet/libpnet#726]
`cargo expand`:

```rust
/// The size (in bytes) of a Tcp instance when converted into
/// a byte-array
#[inline]
pub fn packet_size(_packet: &Tcp) -> usize {
    20 + _packet.options.len() + _packet.payload.len()
}
```

Unfortunately, `options` is a `Vec<TcpOption>`, and each `TcpOption` is more than one byte. Thus, the calculated size is too small. This means the following breaks:

```rust
let tcp_raw = [0x10, 0x92, 0x80, 0x6e, 0x5f, 0x9d, 0xb1, 0xae, 0xc7, 0x25, 0xe9, 0xb1, 0x60, 0x12, 0x06, 0x00, 0xba, 0xee, 0x00, 0x00, 0x02, 0x04, 0x05, 0xb4];
let tcp_packet: TcpPacket<'_> = TcpPacket::new(&tcp_raw).unwrap();
let tcp: Tcp = tcp_packet.from_packet();
println!("{tcp:?}");
let mut buffer: Vec<u8> = vec![0; MutableTcpPacket::packet_size(&tcp)];
MutableTcpPacket::new(&mut buffer).unwrap().populate(&tcp);
```

Output:
```
Tcp { source: 4242, destination: 32878, sequence: 1604170158, acknowledgement: 3341150641, data_offset: 6, reserved: 0, flags: 18, window: 1536, checksum: 47854, urgent_ptr: 0, options: [TcpOption { number: TcpOptionNumber(2), length: [4], data: [5, 180] }], payload: [] }
thread 'runner::input::parsed::tests::parse_tcp' panicked at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pnet_packet-0.35.0/src/tcp.rs:107:1:
range end index 2 out of range for slice of length 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:64:5
   3: core::slice::index::slice_end_index_len_fail
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:57:5
   4: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:479:13
   5: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:27:9
   6: <pnet_macros_support::packet::MutPacketData as core::ops::index::IndexMut<core::ops::range::Range<usize>>>::index_mut
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pnet_macros_support-0.35.0/src/packet.rs:108:17
   7: pnet_packet::tcp::MutableTcpOptionPacket::set_length
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pnet_packet-0.35.0/src/tcp.rs:107:1
   8: pnet_packet::tcp::MutableTcpOptionPacket::populate
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pnet_packet-0.35.0/src/tcp.rs:107:1
   9: pnet_packet::tcp::MutableTcpPacket::set_options
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pnet_packet-0.35.0/src/tcp.rs:56:1
  10: pnet_packet::tcp::MutableTcpPacket::populate
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pnet_packet-0.35.0/src/tcp.rs:56:1
  11: fuzzer::runner::input::parsed::tests::parse_tcp
             at ./src/runner/input/parsed.rs:154:9
  12: fuzzer::runner::input::parsed::tests::parse_tcp::{{closure}}
             at ./src/runner/input/parsed.rs:144:19
  13: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This is how the length should be calculated:
```rust
let tcp_raw = [0x10, 0x92, 0x80, 0x6e, 0x5f, 0x9d, 0xb1, 0xae, 0xc7, 0x25, 0xe9, 0xb1, 0x60, 0x12, 0x06, 0x00, 0xba, 0xee, 0x00, 0x00, 0x02, 0x04, 0x05, 0xb4];

let tcp_packet: TcpPacket<'_> = TcpPacket::new(&tcp_raw).unwrap();
let tcp: Tcp = tcp_packet.from_packet();
println!("{tcp:?}");
let len = MutableTcpPacket::minimum_packet_size()
    + tcp
        .options
        .iter()
        .map(TcpOptionPacket::packet_size)
        .sum::<usize>()
    + tcp.payload.len();
let mut buffer: Vec<u8> = vec![0; len];
MutableTcpPacket::new(&mut buffer).unwrap().populate(&tcp);```

**Comment by riesentoaster** [comment]
See also #519.

**Comment by lance0** [comment]
Opened PR: https://github.com/libpnet/libpnet/pull/759

This fixes the `#[packet]` struct-side `packet_size()` undercount for `Vec<#[packet]>` fields by summing per-item packet sizes instead of using `.len()`.

Regression coverage:
- Added/updated nested packet-size assertion in `pnet_macros/tests/run-pass/packet_in_packet.rs`.

To keep CI green on current stable, the PR also includes:
- `trybuild` snapshot updates in `pnet_macros/tests/compile-fail/*`
- explicit lifetime annotations needed under warning-deny in `pnet_packet/src/ipv6.rs` and `pnet_transport/src/lib.rs`

Current PR checks are green.
