### ISSUE TITLE
remove code duplication for rfc1071 checksum

### ISSUE THREAD

**Issue by david415** [libpnet/libpnet#91]
I noticed there is a checksum function for IPv4 and for UDP... and they are nearly identical... I am looking into writing a checksum helper function for TCP... and but instead all three of these protocols should share the same checksum function.

Here's an example of good abstraction for providing checksums for all these protocols:
https://github.com/google/gopacket/blob/master/layers/tcpip.go

That is... the checksum helper function for each protocol becomes a thin shim who is only responsible for gathering the header fields into a buffer. Then the checksum function operates on this buffer and returns the resulting checksum value.

**Comment by mrmonday** [comment]
I'd happily accept a pull request removing the duplication if you want to throw one together - I don't have time to work on this myself right now unfortunately.

**Comment by david415** [comment]
Yes... I'm here to help out with code contributions. This ticket is now tied to #90 because I'm writing a set of helper functions for TCP encoding... I should be able to fix this in a few days or so.

**Comment by david415** [comment]
Furthermore we should do like gopacket does and abstract away the details of computing the pseudo-header; in fact we don't even need to create a pseudo-header... nor do we want to since memory copy is inefficient.

Instead we realize the since the checksum is based on addition and is therefore commutative and associative; we simply compute "some" pseudo-header checksum value... (either for IPv4 or IPv4) and then continue ADDing to it in order to compute the TCP checksum.

**Comment by david415** [comment]
here in my dev branch i've created a function to compute the ipv4 pseudo header... and a generic rfc1071 checksum function.... i also added the trait HasPseudoheader... so that both IPv4Packet and IPv6Packet and implement this trait:
https://github.com/david415/libpnet/tree/91.add-modular-checksum.0

the trouble is that is that I'm relatively new to rust and i can't get it to build yet:
```
user@debian-rust:~/projects/libpnet/src/packet$ cargo test
   Compiling pnet v0.0.1 (file:///home/user/projects/libpnet)
/home/user/projects/libpnet/src/packet/ipv4.rs:42:26: 42:36 error: wrong number of lifetime parameters: expected 1, found 0 [E0107]
/home/user/projects/libpnet/src/packet/ipv4.rs:42 impl HasPseudoheader for Ipv4Packet {
                                                                           ^~~~~~~~~~
/home/user/projects/libpnet/src/packet/ipv4.rs:42:26: 42:36 help: run `rustc --explain E0107` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
/home/user/projects/libpnet/src/packet/ipv4.rs:42:26: 42:36 error: wrong number of lifetime parameters: expected 1, found 0 [E0107]
/home/user/projects/libpnet/src/packet/ipv4.rs:42 impl HasPseudoheader for Ipv4Packet {
                                                                           ^~~~~~~~~~
/home/user/projects/libpnet/src/packet/ipv4.rs:42:26: 42:36 help: run `rustc --explain E0107` to see a detailed explanation
error: aborting due to previous error
Could not compile `pnet`.

To learn more, run the command again with --verbose.
user@debian-rust:~/projects/libpnet/src/packet$ 
```

**Comment by david415** [comment]
ok I got my dev branch to build... clearly the next step is to implement the modular TCP checksum function which uses the HasPseudoheader trait to compute the first part of the checksum. This TCP checksum doesn't care if it's TCP header is inside a IPv4 or IPv6 packet... it just concerns itself with passing the serialized TCP header + payload to the generic checksum function...

**Comment by david415** [comment]
in this dev branch i demonstrate a modular tcp checksum which not only shares code with the ipv4 checksum function but also is agnostic as to whether the tcp packet is encapsulated by ipv4 or ipv6...

https://github.com/david415/libpnet/tree/90.add-tcp-packet.1

however... i was unable to get my unit test doesn't work and i think this has to do with the optional field lengths because of this build error:
```
---- packet::tcp::tests::tcp_header_ipv4_test stdout ----
	thread 'packet::tcp::tests::tcp_header_ipv4_test' panicked at 'assertion failed: current_offset <= len', /home/user/projects/libpnet/src/packet/tcp.rs:17
```

maybe you can help with this?
the tcp data offset is a count of 32 bit words the comprise the entire tcp header; the minimum size being 5 (20 bytes)...

**Comment by david415** [comment]
here's the modular code sharing and ipv4 versus ipv6 agnostic tcp checksum function:
```
/// Calculates the checksum of a TCP packet
pub fn checksum<'a, T: HasPseudoheader>(packet: &mut MutableTcpPacket<'a>, encapsulating_packet: T) -> u16be {
let mut sum = encapsulating_packet.pseudoheader_checksum();
let length = packet.packet().len() as u32;
sum = sum + length & 0xffff;
sum = sum + length >> 16;
packet.set_checksum(0);
return rfc1071_checksum(packet.packet(), sum);
}
```

...because i've created the ipv6 pseudoheader implementation of the HasPseudoheader trait... the above function of course works with ipv6. We can easily write a similarly modular checksum function from UDP.

i've also created a similarly simple ipv4 checksum function:

```
/// Calculates the checksum of an IPv4 packet
pub fn checksum<'a>(packet: &Ipv4Packet<'a>) -> u16be {
    use packet::Packet;

    return rfc1071_checksum(packet.packet(), 0);
}
```

**Comment by david415** [comment]
currently this ticket is blocked on fixing the unit test for ipv4 + tcp checksum; i get these kind of errors indicating my length method must be wrong:

```
---- packet::tcp::tests::tcp_header_ipv4_test stdout ----
	thread 'packet::tcp::tests::tcp_header_ipv4_test' panicked at 'assertion failed: index < self.len()', ../src/libcore/slice.rs:521
```

**Comment by mrmonday** [comment]
You should take a look at the backtrace to see where in your code it's failing - we can work from there. You may need to set RUST_BACKTRACE=1 to get a backtrace.

**Comment by david415** [comment]
my latest dev branch:
https://github.com/david415/libpnet/tree/90.add-tcp-packet.1

currently the test fails like this:
```
---- packet::tcp::tests::tcp_header_ipv4_test stdout ----
	thread 'packet::tcp::tests::tcp_header_ipv4_test' panicked at 'assertion failed: current_offset <= len', src/packet/tcp.rs:17

stack backtrace:
   1:     0x7f3bebc6e17e - sys::backtrace::write::h3ecf23ae317178b4Qqs
   2:     0x7f3bebc75e14 - panicking::on_panic::hffb5f62afcb56dacQ9w
   3:     0x7f3bebc38d9e - rt::unwind::begin_unwind_inner::ha7a91c9abe288335uPw
   4:     0x7f3bec629d9c - rt::unwind::begin_unwind::h15872786865703440783
                        at ../src/libstd/rt/unwind/mod.rs:226
   5:     0x7f3bec6352a2 - packet::tcp::MutableTcpPacket<'a>::set_options::h235200d9f17f35819Vf
                        at /home/user/projects/libpnet/<std macros>:3
   6:     0x7f3bec638590 - packet::tcp::tests::generate_simple_tcp_header::h9ac21d6225d453b4LNg
                        at src/packet/tcp.rs:197
   7:     0x7f3bec636b52 - packet::tcp::tests::tcp_header_ipv4_test::ha8bc028784fd645eYHg
                        at src/packet/tcp.rs:128
   8:     0x7f3bec1c212b - boxed::F.FnBox<A>::call_box::h10883720166646750684
   9:     0x7f3bec1c4d72 - boxed::F.FnBox<A>::call_box::h1874595457135913902
  10:     0x7f3bec1c28f9 - rt::unwind::try::try_fn::h8138678524071760861
  11:     0x7f3bebcf0e78 - rust_try_inner
  12:     0x7f3bebcf0e65 - rust_try
  13:     0x7f3bebc614b7 - rt::unwind::try::inner_try::h497973a2166ac637nLw
  14:     0x7f3bec1c2b0b - boxed::F.FnBox<A>::call_box::h1009659131316280359
  15:     0x7f3bebc74a71 - sys::thread::Thread::new::thread_start::h1bd024404d1992a3aVv
  16:     0x7f3beaf4d0a3 - start_thread
  17:     0x7f3beb8c604c - clone
  18:                0x0 - <unknown>
```

**Comment by mrmonday** [comment]
This appears to be an issue in `pnet_macros`, the code which is failing is generated at [pnet_macros/src/decorator.rs:624](https://github.com/libpnet/libpnet/blob/master/pnet_macros/src/decorator.rs#L624). This method should really return a `Result` rather than asserting. I've opened issue #99 for this.

Assuming the generated code is correct (it's possible that it isn't), the issue is that there isn't sufficient space in the packet for the vector of items you're trying to insert.

**Comment by david415** [comment]
@little-dude has fixed some of the bugs in the modular checksum approach in his branch:
https://github.com/libpnet/libpnet/pull/146

here's my work in progress
https://github.com/libpnet/libpnet/pull/150

**Comment by david415** [comment]
here's my latest dev branch based off of a recent commit on upstream master:
https://github.com/david415/libpnet/tree/91.add-modular-checksum.3

i might have missed some bits of code from out previous dev branches... not sure yet because i've been unable to get it to compile so i haven't yet started to work on the tests.

{{{
/home/human/code/libpnet/target/release/build/pnet-b590d00bedd3d3df/out/ipv4.rs:1135:13: 1135:25 error: slice pattern syntax is experimental (see issu
e #23121)
/home/human/code/libpnet/target/release/build/pnet-b590d00bedd3d3df/out/ipv4.rs:1135             [a, b, c, d] => {
                                                                                                 ^~~~~~~~~~~~
src/packet/ipv4.rs:12:1: 12:48 note: in this expansion of include!
/home/human/code/libpnet/target/release/build/pnet-b590d00bedd3d3df/out/ipv4.rs:1143:13: 1143:25 error: slice pattern syntax is experimental (see iss$e #23121)
/home/human/code/libpnet/target/release/build/pnet-b590d00bedd3d3df/out/ipv4.rs:1143             [a, b, c, d] => {
                                                                                                 ^~~~~~~~~~~~
src/packet/ipv4.rs:12:1: 12:48 note: in this expansion of include!
/home/human/code/libpnet/target/release/build/pnet-b590d00bedd3d3df/out/ipv6.rs:974:13: 974:37 error: slice pattern syntax is experimental (see issue #23121)
/home/human/code/libpnet/target/release/build/pnet-b590d00bedd3d3df/out/ipv6.rs:974             [a, b, c, d, e, f, g, h] => {
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~
src/packet/ipv6.rs:12:1: 12:48 note: in this expansion of include!
/home/human/code/libpnet/target/release/build/pnet-b590d00bedd3d3df/out/ipv6.rs:987:13: 987:37 error: slice pattern syntax is experimental (see issue #23121)
/home/human/code/libpnet/target/release/build/pnet-b590d00bedd3d3df/out/ipv6.rs:987             [a, b, c, d, e, f, g, h] => {
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~
src/packet/ipv6.rs:12:1: 12:48 note: in this expansion of include!
error: aborting due to 4 previous errors
Could not compile `pnet`.
}}}

**Comment by mrmonday** [comment]
[I edited your comment to fix the formatting, I hope you don't mind]

It looks like you've lost a lot of changes - the slice patterns stuff was removed in e9573fa2, back at the start of December.

**Comment by david415** [comment]
ok i got rid of the slice syntax and made a few more commits.
it now builds but has these compiler warnings:

```
# make
bash build.sh
   Compiling pnet v0.9.0 (file:///home/human/code/libpnet)
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:455:13: 455:37 warning: unused import, #[warn(unused_imports)] on by default
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:455         use pnet::packet::FromPacket;
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:455:13: 455:37 note: in this expansion of include!
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:721:13: 721:37 warning: unused import, #[warn(unused_imports)] on by default
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:721         use pnet::packet::FromPacket;
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:721:13: 721:37 note: in this expansion of include!
```

how the tests do not build or execute:
```
# make test
bash build.sh test
   Compiling pnet_macros v0.8.1 (file:///home/human/code/libpnet/pnet_macros)
src/decorator.rs:329:44: 329:68 error: failed to resolve. Could not find `IdentStyle` in `syntax::parse::token` [E0433]
src/decorator.rs:329             Token(span, token::Ident(name, token::IdentStyle::Plain)) => {
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~
src/decorator.rs:329:44: 329:68 help: run `rustc --explain E0433` to see a detailed explanation
src/decorator.rs:348:38: 348:64 error: failed to resolve. Could not find `IdentStyle` in `syntax::parse::token` [E0433]
src/decorator.rs:348             Token(_, token::Ident(_, token::IdentStyle::ModName)) => {
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/decorator.rs:348:38: 348:64 help: run `rustc --explain E0433` to see a detailed explanation
src/decorator.rs:329:25: 329:69 error: this pattern has 2 fields, but the corresponding variant has 1 field [E0023]
src/decorator.rs:329             Token(span, token::Ident(name, token::IdentStyle::Plain)) => {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/decorator.rs:329:25: 329:69 help: run `rustc --explain E0023` to see a detailed explanation
src/decorator.rs:348:22: 348:65 error: this pattern has 2 fields, but the corresponding variant has 1 field [E0023]
src/decorator.rs:348             Token(_, token::Ident(_, token::IdentStyle::ModName)) => {
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/decorator.rs:348:22: 348:65 help: run `rustc --explain E0023` to see a detailed explanation
error: aborting due to 2 previous errors
error: Could not compile `pnet_macros`.

To learn more, run the command again with --verbose.
Makefile:17: recipe for target 'test' failed
make: *** [test] Error 101
```

**Comment by david415** [comment]
I also worked on @little-dude 's dev branch:
https://github.com/little-dude/libpnet/tree/cksum2
based on that branch i made this one:
https://github.com/david415/libpnet/tree/91.cksum2.0

I then merged upstream master into the branch and manually resolved the merge conflicts. After making minor adjustments I've been unable to get it to build. I get these compiler messages:

```
bash build.sh
   Compiling pnet v0.9.0 (file:///home/human/code/libpnet)
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:1718:13: 1718:60 error: cannot infer an appropriate lifetime for lifetime parameter 'p in function call due to conflicting requirements [E0495]
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:1718             MutableIpv4PseudoHeaderPacket::new(&mut buffer).unwrap();
                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:1718:13: 1718:60 note: in this expansion of include!
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:1714:5: 1733:6 help: consider using an explicit lifetime parameter as shown: fn get_pseudo_header(&self, buffer: &'p mut [u8],
                     inner_packet_length: Option<usize>)
 -> Ipv4PseudoHeaderPacket<'p>
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:1714     fn get_pseudo_header(&self, buffer: &mut [u8],
                                                                                         ^
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv4.rs:1714:5: 1733:6 note: in this expansion of include!
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1845:39: 1845:43 error: no method named `iter` found for type `&packet::ipv6::Ipv6Packet<'p>` in the current scope
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1845         let pseudo_header_iter = self.iter();
                                                                                                                           ^~~~
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1845:39: 1845:43 note: in this expansion of include!
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1845:39: 1845:43 help: items from traits can only be used if the trait is implemented and in scope; the following traits define an item `iter`, perhaps you need to implement one of them:
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1845:39: 1845:43 help: candidate #1: `datalink::EthernetDataLinkReceiver`
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1845:39: 1845:43 help: candidate #2: `core::slice::SliceExt`
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1848:31: 1848:54 error: no method named `set_next_level_protocol` found for type `packet::ipv6::MutableIpv6PseudoHeaderPacket<'_>` in the current scope
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1848                 pseudo_header.set_next_level_protocol(header.get_next_header());
                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1848:31: 1848:54 note: in this expansion of include!
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1854:51: 1855:60 error: mismatched types [E0308]
/home/human/code/libpnet/target/release/build/pnet-ab3bf8032717ac50/out/ipv6.rs:1854             pseudo_header.set_inner_packet_length(inner_packet_length as

....
```

**Comment by david415** [comment]
aha i think i found a more recent dev branch that is closer to working. anyhow i merged upstream master into it and began fixing some of the compiler errors/warnings. here it is:

https://github.com/david415/libpnet/tree/146.add-modular-checksum.4
